[server]
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
maxUploadSize = 200
runOnSave = true
enableWebsocketCompression = true
maxMessageSize = 200
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[runner]
fastReruns = true
magicEnabled = false
installTracer = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[global]
developmentMode = false
disableWatchdogWarning = true 